name: Manual Run - Detailed Report

on:
  workflow_dispatch:

jobs:
  run-detailed-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Detailed Report
        run: python detailed_report.py
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_TOKEN }}
          DETAILED_REPORT_PARENT_PAGE_ID: ${{ secrets.EMP_TOTALS_PARENT_PAGE_ID }}
